version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=ana
      - POSTGRES_DB=my_db
    networks:
      - external_network

networks:
  external_network:
    external: true